version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "infra"
    reviewers:
      - marysaka
    commit-message:
      prefix: "ci"

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
    labels:
      - "infra"
    reviewers:
      - marysaka
    commit-message:
      prefix: nuget
    groups:
      Avalonia:
        patterns:
          - "*Avalonia*"
      Silk.NET:
        patterns:
          - "Silk.NET*"
      OpenTK:
        patterns:
          - "OpenTK*"
      SixLabors:
        patterns:
          - "SixLabors*"
      Ryujinx:
        patterns:
          - "Ryujinx*"
