name: Bug Report
description: File a bug report
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: input
    id: issue
    attributes:
      label: Description of Issue
      description: What's the issue you encountered?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: How can the issue be reproduced?
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Log File
      description: A log file will help our developers to better diagnose and fix the issue.
      placeholder: Logs files can be found under "Logs" folder in Ryujinx program folder. You can drag and drop the log on to the textarea
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      value: |
        - *(e.g. Windows 10)*
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment?
      value: |
        - ##### CPU: *(e.g. i7-6700)*
        - ##### GPU: *(e.g. NVIDIA RTX 2070)*
        - ##### RAM: *(e.g. 16GB)*
        - Applied Mods: [ Yes (Which ones) / No ]
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context?
      description: |
      - Additional info about your environment:
      - [ Any other information relevant to your issue. ]
    validations:
      required: false