name: Feature Request
description: Suggest a new feature for Ryujinx.
body:
  - type: input
    id: feature
    attributes:
      label: Overview
      description: Include the basic, high-level concepts for this feature here.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: smaller details
      description: These may include specific methods of implementation etc.
    validations:
      required: true
  - type: textarea
    id: request
    attributes:
      label: Nature of Request
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Why would this feature be useful?
    validations:
      required: true
