name: Feature Request
description: Suggest a new feature for Ryujinx.
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you are requesting.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: Include the basic, high-level concepts for this feature here.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Smaller Details
      description: These may include specific methods of implementation etc.
    validations:
      required: true
  - type: textarea
    id: request
    attributes:
      label: Nature of Request
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Why would this feature be useful?
    validations:
      required: true
