name: Missing CPU Instruction
description: CPU Instruction is missing in Ryujinx.
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search for existing missing CPU instruction
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: instruction
    attributes:
      label: CPU instruction
      description: What CPU instruction is missing?
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Smaller Details
      description: These may include specific methods of implementation etc.
    validations:
      required: true
  - type: textarea
    id: name
    attributes:
      label: Instruction name
      description: Include the name from [armconverter.com](https://armconverter.com/?disasm) or [shell-storm.org](http://shell-storm.org/online/Online-Assembler-and-Disassembler/?arch=arm64&endianness=big&dis_with_raw=True&dis_with_ins=True) in the above code block
    validations:
      required: true
  - type: textarea
    id: required
    attributes:
      label: Required by
      description: Add our games list database (https://github.com/Ryujinx/Ryujinx-Games-List/issues) links of games who require this instruction
    validations:
      required: true
