name: Missing Service Call
description: Service call is missing in Ryujinx.
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search for existing missing service call
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: instruction
    attributes:
      label: Service Call
      description: What service call is missing?
    validations:
      required: true
  - type: textarea
    id: name
    attributes:
      label: Service description
      description: Include the description/explanation from (https://switchbrew.org/w/index.php?title=Services_API) and/or (https://reswitched.github.io/SwIPC/) in the above code block
    validations:
      required: true
  - type: textarea
    id: required
    attributes:
      label: Required by
      description: Add our games list database (https://github.com/Ryujinx/Ryujinx-Games-List/issues) links of games who require this instruction
    validations:
      required: true