name: Perform checks

on:
  pull_request:
    branches: [ master ]
    paths:
      - '**'
      - '!.github/**'
      - '!*.yml'
      - '!*.config'
      - '!README.md'
      - '.github/workflows/*.yml'

permissions:
  pull-requests: write
  checks: write

concurrency:
  group: pr-checks-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - run: dotnet restore

      - name: Run dotnet format
        run: |
          dotnet format --verify-no-changes --report ./report.json -v d

      - name: Upload report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-format
          path: ./report.json

  pr_build:
    uses: ./.github/workflows/build.yml
    needs: format
    secrets: inherit
