name: Format check job

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - 'master'
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - uses: xt0rted/dotnet-format-problem-matcher@v1
    - name: Install dotnet format
      run: dotnet tool install -g dotnet-format
    - name: Check Format
      run: dotnet format -w Ryujinx.sln --check --dry-run --verbosity diagnostic