name: "Pull Request Triage"
on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      # Grab sources to get latest labeler.yml
      - name: Fetch sources
        uses: actions/checkout@v4
        with:
           # Ensure we pin the source origin as pull_request_target run under forks.
           fetch-depth: 0
           repository: Ryujinx/Ryujinx
           ref: master

      - name: Checkout Ryujinx-Mako
        uses: actions/checkout@v4
        with:
            repository: Ryujinx/Ryujinx-Mako
            ref: master
            path: '.ryujinx-mako'

      - name: Setup Ryujinx-Mako
        uses: ./.ryujinx-mako/.github/actions/setup-mako

      - name: Update labels based on changes
        uses: actions/labeler@v4
        with:
          sync-labels: true
          dot: true

      - name: Assign reviewers
        run: |
            poetry -C .ryujinx-mako shell
            ryujinx-mako update-reviewers ${{ github.repository }} ${{ github.event.pull_request.number }} .github/reviewers.yml
        shell: bash
        env:
            MAKO_APP_ID: ${{ secrets.MAKO_APP_ID }}
            MAKO_PRIVATE_KEY: ${{ secrets.MAKO_PRIVATE_KEY }}
            MAKO_INSTALLATION_ID: ${{ secrets.MAKO_INSTALLATION_ID }}
